name: product_list_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  ## State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  ## Dependency Injector
  get_it: ^7.6.0

  ## API Calls
  dio: ^5.2.1+1

  ## Data Connection Checker
  connectivity_plus: ^4.0.1

  json_annotation: ^4.8.1
  json_serializable: ^6.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
